public enum PlayerEvent
{
    InteractingDoor,
    InteractingElevator,
    InteractingLocker,
    Spawned,
    Died,
    UsingItem,
    UsedItem,
    Hurting,
    Hurt,
    Dying,
    Shooting,
    Shot,
    ChangingItem,
    TriggeringTesla,
    UsingRadioBattery,
    FlippingCoin,
    MakingNoise,
    Jumping,
    Transmitting,
    KillPlayer,
    DamagingDoor
}